"""
plot_alpha_running_jegerlehner.py

One-loop running of alpha_EM(M) using Jegerlehner's data-driven hadronic
vacuum polarisation Delta alpha_had^(5)(s) instead of pQCD with
effective light-quark masses. This is the AN-quality version of
plot_alpha_running.py and plot_alpha_running_exact.py:

- Hadronic Delta alpha_had^(5)(s):
      Tabulated by Jegerlehner's alphaQEDc23 routine `dhadr5x` (Fortran),
      based on a dispersion integral over e+e- -> hadrons cross-section
      data. Delta alpha_had^(5)(M_Z^2) = 0.02760 +/- 0.00015 (from this
      package's tabulated central value), consistent within errors with
      the Burkhardt-Pietrzyk and Davier-Hoecker values.

      Sourced from F. Jegerlehner, alphaQEDc23 package
      (https://people.physik.hu-berlin.de/~fjeger/software.html).
      The tabulated grid `dalpha_had_jeg23.txt` (alongside this script)
      is regenerated by compiling `hadr5x23.f` from alphaQEDc23 against
      the driver `drive_dahad.f` (alongside this script); see the
      regeneration recipe at the bottom of this docstring.

- Charged leptons & top quark: literal one-loop dispersion form
      Delta alpha_f(s) = (2 alpha_0 / pi) Q^2 N_c
                         * Re int_0^1 dx x(1-x) ln|1 - x(1-x) s/m^2|
  Same as plot_alpha_running_exact.py.

- W boson: B_0-based ansatz matched to canonical LL slope
      Delta alpha_W(s) = (7 alpha_0 / 12 pi) * Re Bbar_0(s, M_W, M_W)
  Captures the cusp at s = 4 M_W^2 and matches LL -(7 alpha/12pi)
  ln(s/M_W^2) at high s. Differs from the literal full bosonic VP
  by an O(alpha) finite constant (see plot_alpha_running_exact.py
  docstring for the diagram-set caveat).

Recipe to regenerate the hadronic grid:
    # 1. Fetch alphaQEDc23 from Jegerlehner's site:
    curl -kO https://people.physik.hu-berlin.de/~fjeger/hadr5x23.f
    # 2. Build the driver alongside it:
    cp <repo>/calibration_studies/lineshape/alpha_running/drive_dahad.f .
    gfortran -O2 -fno-second-underscore -std=legacy -o drive_dahad \\
        drive_dahad.f hadr5x23.f
    # 3. Dump the grid:
    echo "0.3 1500.0 5000" | ./drive_dahad > \\
        <repo>/calibration_studies/lineshape/alpha_running/dalpha_had_jeg23.txt

Run with the mfs venv:
    source ../../../mfs/.venv/bin/activate
    python plot_alpha_running_jegerlehner.py
"""

import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from scipy.integrate import quad
import mplhep as hep

hep.style.use(hep.style.ROOT)
plt.rcParams.update({'font.size': 16})

OUTPUT_DIR = "/work/submit/david_w/Documents/AN-EN-XXX/plots"
HAD_TABLE  = os.path.join(os.path.dirname(__file__), "dalpha_had_jeg23.txt")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
ALPHA_0 = 1.0 / 137.036
MZ      = 91.1876
M_TOP   = 172.76
M_W     = 80.377

LEPTONS = [('e',   5.110e-4),
           ('mu',  0.10566),
           ('tau', 1.7769)]


# ---------------------------------------------------------------------------
# Hadronic VP: load Jegerlehner alphaQEDc23 grid and interpolate
# ---------------------------------------------------------------------------

def _load_had_grid():
    e, der, errder = np.loadtxt(HAD_TABLE, unpack=True)
    return e, der, errder


_HAD_E, _HAD_DER, _HAD_ERR = _load_had_grid()
_HAD_LOG_E = np.log(_HAD_E)


def delta_alpha_had(M):
    """Linear interpolation of Jegerlehner Delta alpha_had^(5) on log E."""
    le = np.log(M)
    return np.interp(le, _HAD_LOG_E, _HAD_DER,
                     left=_HAD_DER[0], right=_HAD_DER[-1])


def delta_alpha_had_err(M):
    le = np.log(M)
    return np.interp(le, _HAD_LOG_E, _HAD_ERR,
                     left=_HAD_ERR[0], right=_HAD_ERR[-1])


# ---------------------------------------------------------------------------
# Subtracted Passarino-Veltman B_0 with equal masses (real part)
# ---------------------------------------------------------------------------

def B0_bar_real(s, m):
    """Re[B_0(s, m, m) - B_0(0, m, m)]; vanishes at s=0; finite cusp at s=4m^2."""
    if s == 0.0:
        return 0.0
    z = s / (m * m)
    if z < 0:
        beta = np.sqrt(1.0 - 4.0/z)
        return 2.0 - beta * np.log((beta + 1.0) / (beta - 1.0))
    elif z < 4.0:
        beta_p = np.sqrt(4.0/z - 1.0)
        return 2.0 - 2.0 * beta_p * np.arctan(1.0 / beta_p)
    elif z == 4.0:
        return 2.0
    else:
        beta = np.sqrt(1.0 - 4.0/z)
        return 2.0 - beta * np.log((1.0 + beta) / (1.0 - beta))


# ---------------------------------------------------------------------------
# Exact one-loop fermion VP (real part)
# ---------------------------------------------------------------------------

def delta_alpha_fermion_exact(s, m, charge, Nc):
    if s <= 0.0 or m <= 0.0:
        return 0.0
    z = s / (m * m)

    def integrand(x):
        arg = 1.0 - x * (1.0 - x) * z
        if arg == 0.0:
            return 0.0
        return x * (1.0 - x) * np.log(abs(arg))

    integral, _ = quad(integrand, 0.0, 1.0, limit=300, epsabs=1e-14, epsrel=1e-10)
    return (2.0 * ALPHA_0 / np.pi) * charge ** 2 * Nc * integral


# ---------------------------------------------------------------------------
# Component sums
# ---------------------------------------------------------------------------

def delta_alpha_lep(M):
    s = M * M
    return sum(delta_alpha_fermion_exact(s, ml, 1.0, 1) for _, ml in LEPTONS)


def delta_alpha_top(M):
    return delta_alpha_fermion_exact(M * M, M_TOP, 2.0/3.0, 3)


def delta_alpha_W(M):
    return (7.0 * ALPHA_0 / (12.0 * np.pi)) * B0_bar_real(M * M, M_W)


def delta_alpha_total(M):
    return (delta_alpha_lep(M) + delta_alpha_had(M)
            + delta_alpha_top(M) + delta_alpha_W(M))


# ---------------------------------------------------------------------------
# Build grids
# ---------------------------------------------------------------------------
M_grid_log = np.logspace(np.log10(1.0), np.log10(1000.0), 600)
M_grid_W   = np.linspace(2*M_W - 5, 2*M_W + 30, 200)
M_grid_t   = np.linspace(2*M_TOP - 10, 2*M_TOP + 60, 200)
M_grid     = np.unique(np.concatenate([M_grid_log, M_grid_W, M_grid_t]))
M_grid     = M_grid[M_grid > 0]

print(f"Computing {len(M_grid)} grid points...")
dal_lep = np.array([delta_alpha_lep(m) for m in M_grid])
dal_had = np.array([delta_alpha_had(m) for m in M_grid])
dal_err = np.array([delta_alpha_had_err(m) for m in M_grid])
dal_top = np.array([delta_alpha_top(m) for m in M_grid])
dal_W   = np.array([delta_alpha_W(m)   for m in M_grid])
dal_tot = dal_lep + dal_had + dal_top + dal_W
ialpha  = (1.0 - dal_tot) / ALPHA_0
print("Done.")


def report(M):
    print(f"  M = {M:7.2f} GeV: 1/alpha = {(1-delta_alpha_total(M))/ALPHA_0:.3f}, "
          f"Da_had = {delta_alpha_had(M):+.5f} +- {delta_alpha_had_err(M):.5f}, "
          f"Da_W = {delta_alpha_W(M):+.5f}, Da_top = {delta_alpha_top(M):+.5f}")

print("Sanity checks:")
for M in (1.0, 5.0, 10.0, MZ, 2*M_W, 200.0, 2*M_TOP, 1000.0):
    report(M)

# ---------------------------------------------------------------------------
# Plot
# ---------------------------------------------------------------------------
fig, (ax_top, ax_bot) = plt.subplots(
    2, 1, figsize=(6, 8),
    gridspec_kw={"height_ratios": [2, 3], "hspace": 0.05},
)

ax_top.plot(M_grid, ialpha, color='black', lw=2.0)
ax_top.fill_between(M_grid, ialpha - dal_err / ALPHA_0,
                    ialpha + dal_err / ALPHA_0, color='black', alpha=0.20)
ax_top.axvline(MZ,      color='grey', lw=0.9, ls='--')
ax_top.axvline(2*M_W,   color='C2',   lw=0.7, ls=':', alpha=0.7)
ax_top.axvline(2*M_TOP, color='C4',   lw=0.7, ls=':', alpha=0.7)
ax_top.set_xscale('log')
ax_top.set_xlim(M_grid[0], M_grid[-1])
# Clip y-axis so the J/psi, psi(2S), Upsilon resonance pole-like swings in
# Re Delta alpha_had do not dominate the figure. The narrow features going
# off-scale at ~3.1, ~3.7, ~9.5-10.5 GeV are the expected dispersive
# resonance structure.
ax_top.set_ylim(124, 138)
ax_top.set_ylabel(r'$1/\alpha(M)$')
ax_top.tick_params(labelbottom=False)
ax_top.yaxis.set_major_locator(ticker.MaxNLocator(5, prune='both'))
ymin, _ = ax_top.get_ylim()
ax_top.text(MZ * 1.06,    ymin + 0.5, r'$M_Z$',  fontsize=12, color='grey', va='bottom')
ax_top.text(2*M_W * 1.04, ymin + 0.5, r'$2M_W$', fontsize=11, color='C2',   va='bottom')
ax_top.text(2*M_TOP*1.04, ymin + 0.5, r'$2m_t$', fontsize=11, color='C4',   va='bottom')

ax_bot.plot(M_grid, dal_lep, color='C0', lw=2.0,
            label=r'$\Delta\alpha_\mathrm{lep}$')
ax_bot.plot(M_grid, dal_had, color='C3', lw=2.0,
            label=r'$\Delta\alpha_\mathrm{had}^{(5)}$ (alphaQEDc23)')
ax_bot.fill_between(M_grid, dal_had - dal_err, dal_had + dal_err,
                    color='C3', alpha=0.30)
ax_bot.plot(M_grid, dal_W,   color='C2', lw=2.0,
            label=r'$\Delta\alpha_W$')
ax_bot.plot(M_grid, dal_top, color='C4', lw=2.0,
            label=r'$\Delta\alpha_\mathrm{top}$')
ax_bot.plot(M_grid, dal_tot, color='black', lw=2.0,
            label=r'$\Delta\alpha_\mathrm{total}$')
ax_bot.fill_between(M_grid, dal_tot - dal_err, dal_tot + dal_err,
                    color='grey', alpha=0.30)
ax_bot.axvline(MZ,      color='grey', lw=0.9, ls='--')
ax_bot.axvline(2*M_W,   color='C2',   lw=0.7, ls=':', alpha=0.7)
ax_bot.axvline(2*M_TOP, color='C4',   lw=0.7, ls=':', alpha=0.7)
ax_bot.axhline(0,       color='grey', lw=0.7, ls=':')
ax_bot.set_xscale('log')
ax_bot.set_xlim(M_grid[0], M_grid[-1])
ax_bot.set_ylim(-0.005, 0.10)
ax_bot.set_xlabel(r'$M$ (GeV)')
ax_bot.set_ylabel(r'$\Delta\alpha(M)$')
ax_bot.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'{x:g}'))
ax_bot.legend(loc='upper left', fontsize=11, framealpha=0.9, ncol=2)

for ext in ('pdf', 'png'):
    path = os.path.join(OUTPUT_DIR, f'alpha_running_jegerlehner.{ext}')
    fig.savefig(path, dpi=150 if ext == 'png' else None, bbox_inches='tight')
    print(f'Saved: {path}')
plt.close(fig)
